services:
  dataset-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=1
    volumes:
      - ../data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
